# Generated by Django 4.2.6 on 2023-11-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=25, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('release_date', models.DateField()),
                ('certification', models.CharField(max_length=10)),
                ('runtime', models.IntegerField()),
                ('director', models.CharField(max_length=50)),
            ],
        ),
    ]
